### ISSUE TITLE
CREATE SCHEMA query can fail with existing object error

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#406]
Saw this in a run of the MultiFunctionTriggerTest test

```
[6572] [2022-10-17T23:19:25.550Z] Failed to start SQL trigger listener for table: 'dbo.Products', function ID: '57bfa3d6e7fc45ea'. Exception: Microsoft.Data.SqlClient.SqlException (0x80131904): There is already an object named 'az_func' in the database.
[6572] [2022-10-17T23:19:25.550Z] CREATE SCHEMA failed due to previous errors.
[6572] [2022-10-17T23:19:25.550Z]    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
[6572] [2022-10-17T23:19:25.550Z]    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
[6572] [2022-10-17T23:19:25.550Z]    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
[6572] [2022-10-17T23:19:25.551Z]    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
[6572] [2022-10-17T23:19:25.551Z]    at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
[6572] [2022-10-17T23:19:25.551Z]    at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
[6572] [2022-10-17T23:19:25.551Z]    at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
[6572] [2022-10-17T23:19:25.551Z]    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
[6572] [2022-10-17T23:19:25.551Z] --- End of stack trace from previous location ---
[6572] [2022-10-17T23:19:25.551Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.CreateSchemaAsync(SqlConnection connection, SqlTransaction transaction, CancellationToken cancellationToken) in D:\a\1\s\src\TriggerBinding\SqlTriggerListener.cs:line 335
[6572] [2022-10-17T23:19:25.551Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.StartAsync(CancellationToken cancellationToken) in D:\a\1\s\src\TriggerBinding\SqlTriggerListener.cs:line 109
[6572] [2022-10-17T23:19:25.551Z] ClientConnectionId:359bc92e-8697-4e67-8460-58c2fb6c2599
[6572] [2022-10-17T23:19:25.551Z] Error Number:2714,State:6,Class:16
[6572] [2022-10-17T23:19:25.567Z] The listener for function 'MultiFunctionTrigger2' was unable to start.
[6572] [2022-10-17T23:19:25.567Z] The listener for function 'MultiFunctionTrigger2' was unable to start. Core Microsoft SqlClient Data Provider: There is already an object named 'az_func' in the database.
```

[Standard_Console_Output.log](https://github.com/Azure/azure-functions-sql-extension/files/9813708/Standard_Console_Output.log)

**Comment by Charles-Gagnon** [comment]
@JatinSanghvi FYI

**Comment by JatinSanghvi** [comment]
Hi Charles, I am unable to repro the issue using SqlCmd or Data Studio. In my case, if there are two connections, the second connection waits at the IF statement and resumes only after the transaction in first connection is committed.

If we can pause just after the IF and before the EXEC statement, this condition should get hit IMO. I could not test it without getting a syntax error due to body-less IF-statement. Possibly making the transaction isolation level `SERIALIZABLE` and taking `UPDLOCK` on `sys.schemas` table should resolve this issue.

**Comment by Charles-Gagnon** [comment]
Yeah I couldn't repro it either, and I'm not sure how it could have happened since I was seeing the same behavior as you with the first waiting. 

A pretty easy solution would be to just keep it as is but then wrap the execute in a try/catch that filters out SqlException exceptions with error code 2714. This is a similar pattern used often in file system access to determine if a file exists and in our case since we never delete these objects it's fine to just ignore the error in those cases. Without a clear repro I'd be slightly concerned that any other attempts to fix it wouldn't actually solve the problem.

**Comment by AmeyaRele** [comment]
> A pretty easy solution would be to just keep it as is but then wrap the execute in a try/catch that filters out SqlException exceptions with error code 2714. This is a similar pattern used often in file system access to determine if a file exists and in our case since we never delete these objects it's fine to just ignore the error in those cases. Without a clear repro I'd be slightly concerned that any other attempts to fix it wouldn't actually solve the problem.
Will go ahead and create a PR with this fix.
