### ISSUE TITLE
Configuration settings with invalid value result in exception

### ISSUE THREAD

**Issue by AmeyaRele** [Azure/azure-functions-sql-extension#435]
Setting `Sql_Trigger_PollingIntervalMs` to an invalid value eg `testValue` results in this exception. Similar exception is thrown for `Sql_Trigger_BatchSize`. 
```
Unhandled exception. Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'EmployeeTrigger' was unable to start.
 ---> System.InvalidOperationException: Failed to convert configuration value at 'Sql_Trigger_PollingIntervalMs' to type 'System.Int32'.
 ---> System.ArgumentException: testValue is not a valid value for Int32. (Parameter 'value')
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s, NumberStyles style, IFormatProvider provider)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
```

**Comment by Charles-Gagnon** [comment]
Chatted offline about this, this is currently expected behavior so closing this and will re-open separate issue for changing the behavior of the scaling support config
