### ISSUE TITLE
Output trigger fails with: Incorrect syntax near the keyword 'with'

### ISSUE THREAD

**Issue by MasDenBy** [Azure/azure-functions-sql-extension#452]
Extension version: 0.1.483-preview
Function runtime: 4.14.0.19631
OS: Windows

Output trigger fails with the following exception

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```
The azure function is just select entities from one database and copies them into a table from another database.
For authentication a user-assigned managed identity is used.

Users have the following roles:
SourceDb: db_datareader
TargetDb: db_datareader, db_datawriter

```
public void Run(
  [TimerTrigger("%DataCollectorTriggerTimer%")] TimerInfo timer,
  [Sql("SELECT * FROM SourceTable", CommandType = CommandType.Text, ConnectionStringSetting = "SourceDb")] Enumerable<Entity> entities,
  [Sql("dbo.TargetTable", ConnectionStringSetting = "TargetDb")] out Entity[] output)
{
  output = entities.ToArray();
}
```

**Comment by chlafreniere** [comment]
Can you provide some info around the SQL database that you're using, @MasDenBy? 
Is it an Azure SQL database, SQL Server instance (either in a VM, or on-prem), or something else?

**Comment by MasDenBy** [comment]
@chlafreniere we use Azure SQL Server.

**Comment by Charles-Gagnon** [comment]
@MasDenBy The binding is using the [OPENJSON](https://learn.microsoft.com/sql/t-sql/functions/openjson-transact-sql) statement which requires SQL Server 2016+. So if you upgrade your server and/or set the compat level to 130+ then you shouldn't see this issue anymore.

I'm going to close this for now as this is expected behavior currently but we'll let you know if we can make any improvements to support older versions!
