### ISSUE TITLE
Tests occasionally crashing after completion

### ISSUE THREAD

**Issue by Charles-Gagnon** [Azure/azure-functions-sql-extension#464]
Saw this in a recent test run. Doesn't happen but would be good to make sure we're not trying to read more content after the test is done. 

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: [. Path '', line 1, position 2134.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Microsoft.Azure.WebJobs.Extensions.Sql.Tests.Integration.SqlTriggerBindingIntegrationTests.<>c__DisplayClass17_0.<WaitForProductChanges>g__MonitorOutputData|0(Object sender, DataReceivedEventArgs e) in D:\a\1\s\test\Integration\SqlTriggerBindingIntegrationTests.cs:line 541
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
```

**Comment by Charles-Gagnon** [comment]
Should be fixed
