### ISSUE TITLE
Specifying identity column in upsert not supported

### ISSUE THREAD

**Issue by jnsvd** [Azure/azure-functions-sql-extension#483]
When binding a record with a value for its corresponding identity column, the following error occurs at runtime in the core functions CLI tool:

```
System.Private.CoreLib: Exception while executing function: Functions.<redacted>. Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. Core Microsoft SqlClient Data Provider: An explicit value for the identity column in table 'dbo.<redacted>' can only be specified when a column list is used and IDENTITY_INSERT is ON.
```

I'm writing my functions in JavaScript. In my usecase, an existing record is updated. According to the [samples](https://github.com/Azure/azure-functions-sql-extension/tree/main/samples/samples-js/AddProductWithIdentityColumnIncluded) in this repository and the expected behavior of the output binding (performing _upserts_), I would expect identity columns to be supported in my usecase.

**Comment by dzsquared** [comment]
@jnsvd  - out of curiosity, is the identity column part of the primary key on the table?

**Comment by jnsvd** [comment]
> @jnsvd  - out of curiosity, is the identity column part of the primary key on the table?

Yes it is (being the only column of the primary key).

**Comment by Charles-Gagnon** [comment]
It currently isn't supported behavior to insert rows with identity columns specified - the primary keys (including identity columns) are used to match rows and if no existing match is found then a new row is inserted with values for the non-primary key columns coming from the passed in values (but only those, primary key values are skipped when inserting new rows)

That seems reasonable for us to support though so I'll leave this open for tracking that.

I'm actually not sure how you managed to get that error - that isn't a scenario that should happen currently. When I try to repro it I just see the item inserted with the identity column value being generated automatically. 

Is this something you can reproduce reliably? It'd be good to see if we're missing something there.

**Comment by Charles-Gagnon** [comment]
Reading over your description again though - could you explain what your use case is exactly? To me it sounds like : 

1. You have a table similar to the sample one - https://github.com/Azure/azure-functions-sql-extension/blob/main/samples/samples-csharp/Database/Tables/ProductsWithIdentity.sql
2. You have a row in that table - e.g. for the sample above `(1, 'MyProduct', 100)`
3. You're calling your function and specifying `productId=1&name=MyProduct&cost=200`
4. You get the error in the original description

Is that correct?

**Comment by jnsvd** [comment]
@Charles-Gagnon I'm using a table similar as the one in the link. However, I'm using it a bit differently:

- I have one function that creates a record by returning it and binding it to `$return`. In the object returned, I provide every field _except_ for the identity column. This works well and a value for the key is auto-generated.
- In a _different_ function, I'm reading the record, alter it and bind it to `context.bindings.<record_binding>`, _with_ specifying the primary key (being an identity column) field. When this function returns, I'm observing the error.

In my use case, I'm reading the record in the second function from the `mssql` client and not through a binding, because this second function is triggered from a Service Bus message and I need payload data for retrieving the record (something that cannot currently be done using function bindings). However, I suspect this is not related to the problem, since I simply bind a regular JavaScript object (also tried wrapping with `JSON.stringify`, which resulted in the same error).

**Comment by Charles-Gagnon** [comment]
Would you be able to provide debug logs so we can see more details about the function execution? This would help a lot with figuring out what's going on in your case. 

You can enable that by adding logLevel to the logging section of your host.json 

```json
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    },
    "logLevel": {
      "default": "Debug"
    }
  }
```

You can either attach it to this issue or e-mail it to me directly.

**Comment by jnsvd** [comment]
@Charles-Gagnon I ran with debug mode enabled.

This is the resulting log:

```
[2022-11-14T08:15:23.385Z] Received FunctionInvocationRequest
[2022-11-14T08:15:23.394Z] Binding transaction: "{\"TransactionID\":3, <redacted>}"
[2022-11-14T08:15:23.403Z] InvocationResponse received for invocation id: 'c04244f8-b869-4d07-8056-544695d4a687'
[2022-11-14T08:15:23.404Z] Sending event Create
[2022-11-14T08:15:23.404Z] Sending event AddAsync
[2022-11-14T08:15:23.404Z] Sending event FlushAsync
[2022-11-14T08:15:23.404Z] TID:33 BEGIN UpsertRowsAsync
[2022-11-14T08:15:23.405Z] Sending event TableInfoCacheHit
[2022-11-14T08:15:23.405Z] Sending event UpsertStart
[2022-11-14T08:15:23.405Z] TID:33 BEGIN UpsertRowsTransaction
[2022-11-14T08:15:23.409Z] Sending exception event: An explicit value for the identity column in table 'dbo.<redacted>' can only be specified when a column list is used and IDENTITY_INSERT is ON.
[2022-11-14T08:15:23.411Z] Sending exception event: An explicit value for the identity column in table 'dbo.<redacted>' can only be specified when a column list is used and IDENTITY_INSERT is ON.
[2022-11-14T08:15:23.412Z] Executed 'Functions.<redacted> (Failed, Id=c04244f8-b869-4d07-8056-544695d4a687, Duration=29ms)
[2022-11-14T08:15:23.412Z] System.Private.CoreLib: Exception while executing function: Functions.<redacted>. Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. Core Microsoft SqlClient Data Provider: An explicit value for the identity column in table 'dbo.<redacted>' can only be specified when a column list is used and IDENTITY_INSERT is ON.
[2022-11-14T08:15:23.413Z] <redacted>/Subscriptions/<redacted>-46aa4fd0-d6ff-4767-b894-389d2158e85a: User message handler complete: Message: SequenceNumber: 9466, Exception: Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.<redacted>
[2022-11-14T08:15:23.413Z]  ---> System.InvalidOperationException: Error while handling parameter _binder after function returned:
[2022-11-14T08:15:23.413Z]  ---> Microsoft.Data.SqlClient.SqlException (0x80131904): An explicit value for the identity column in table 'dbo.<redacted>' can only be specified when a column list is used and IDENTITY_INSERT is ON.
[2022-11-14T08:15:23.413Z]    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
[2022-11-14T08:15:23.413Z]    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
[2022-11-14T08:15:23.413Z]    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
[2022-11-14T08:15:23.413Z]    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
[2022-11-14T08:15:23.413Z]    at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
[2022-11-14T08:15:23.413Z]    at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
[2022-11-14T08:15:23.413Z]    at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
[2022-11-14T08:15:23.413Z]    at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
[2022-11-14T08:15:23.413Z]    at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
[2022-11-14T08:15:23.413Z]    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
[2022-11-14T08:15:23.413Z] --- End of stack trace from previous location ---
[2022-11-14T08:15:23.413Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlAsyncCollector`1.UpsertRowsAsync(IEnumerable`1 rows, SqlAttribute attribute, IConfiguration configuration)
[2022-11-14T08:15:23.413Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlAsyncCollector`1.FlushAsync(CancellationToken cancellationToken)
[2022-11-14T08:15:23.414Z]    at Microsoft.Azure.WebJobs.Host.Bindings.AsyncCollectorValueProvider`2.SetValueAsync(Object value, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AsyncCollector\AsyncCollectorValueProvider.cs:line 49
[2022-11-14T08:15:23.414Z]    at Microsoft.Azure.WebJobs.Binder.Complete(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Runtime\Binder.cs:line 159
[2022-11-14T08:15:23.414Z]    at Microsoft.Azure.WebJobs.Host.Bindings.Runtime.RuntimeValueProvider.SetValueAsync(Object value, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Runtime\RuntimeValueProvider.cs:line 34
[2022-11-14T08:15:23.414Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.ProcessOutputParameters(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 959
[2022-11-14T08:15:23.414Z] ClientConnectionId:b944fde9-c47f-4c9d-adec-5b4484b22d64
[2022-11-14T08:15:23.414Z] Error Number:8101,State:1,Class:16
[2022-11-14T08:15:23.414Z]    --- End of inner exception stack trace ---
[2022-11-14T08:15:23.414Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.ProcessOutputParameters(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 969
[2022-11-14T08:15:23.414Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 544
[2022-11-14T08:15:23.414Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 306
[2022-11-14T08:15:23.414Z]    --- End of inner exception stack trace ---
[2022-11-14T08:15:23.414Z]    at Microsoft.Azure.WebJobs.ServiceBus.MessageProcessor.CompleteProcessingMessageAsync(ServiceBusMessageActions actions, ServiceBusReceivedMessage message, FunctionResult result, CancellationToken cancellationToken)
[2022-11-14T08:15:23.414Z]    at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.ProcessMessageAsync(ProcessMessageEventArgs args)
[2022-11-14T08:15:23.414Z]    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessMessageAsync(ProcessMessageEventArgs args)
[2022-11-14T08:15:23.414Z]    at Azure.Messaging.ServiceBus.ReceiverManager.OnMessageHandler(EventArgs args)
[2022-11-14T08:15:23.414Z]    at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage triggerMessage, CancellationToken cancellationToken), LockToken: 0ea1914c-f8a4-4a73-b030-fc74331502ac
[2022-11-14T08:15:23.414Z] Message processing error (Action=ProcessMessageCallback, EntityPath=<redacted>/Subscriptions/<redacted>, Endpoint=<redacted>)
[2022-11-14T08:15:23.414Z] System.Private.CoreLib: Exception while executing function: Functions.<redacted>. Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. Core Microsoft SqlClient Data Provider: An explicit value for the identity column in table 'dbo.<redacted>' can only be specified when a column list is used and IDENTITY_INSERT is ON.
[2022-11-14T08:15:23.415Z] <redacted>/Subscriptions/<redacted>-46aa4fd0-d6ff-4767-b894-389d2158e85a-Receiver: AbandonAsync start. MessageCount = 1, LockToken = 0ea1914c-f8a4-4a73-b030-fc74331502ac
[2022-11-14T08:15:23.898Z] <redacted>/Subscriptions/<redacted>-46aa4fd0-d6ff-4767-b894-389d2158e85a-Receiver: AbandonAsync done. LockToken = 0ea1914c-f8a4-4a73-b030-fc74331502ac
```

**Comment by jnsvd** [comment]
@Charles-Gagnon To clarify, the log line:

```
[2022-11-14T08:15:23.394Z] Binding transaction: "{\"TransactionID\":3, <redacted>}"
```

is the result of a log statement:

```
context.log.info(`Binding transaction: ${JSON.stringify(context.bindings.transaction)}`);
```

In `function.json`, I have:

```
{
  "bindings": [
    ...,
    {
      "name": "transaction",
      "type": "sql",
      "direction": "out",
      "commandText": "dbo.<redacted>",
      "connectionStringSetting": "SqlConnectionString"
    },
    ...
  ]
}
```

**Comment by Charles-Gagnon** [comment]
Unfortunately, the logs don't provide enough information currently what exactly is going on - I've recently added some extra logging to address this gap but that won't be out for JS functions for a bit. 

If you're able to spend some more time to convert this to a C# function (see the C# sample here for reference : https://github.com/Azure/azure-functions-sql-extension/blob/main/samples/samples-csharp/OutputBindingSamples/AddProductWithIdentityColumnIncluded.cs) and then reference the https://github.com/Azure/azure-functions-sql-extension/releases/tag/v1.0.21-preview version of the package that would help get that extra information quicker. 

Otherwise, I'll let you know when the extension bundle is updated so you can get that for your JS function and we'll continue on there.

**Comment by jnsvd** [comment]
Converting to a C# function is not an option for us right now.

> Otherwise, I'll let you know when the extension bundle is updated so you can get that for your JS function and we'll continue on there.

Please do, I would be happy to run again with more logging (or a fix) provided.

In the meantime, I have switched to using a `uniqueidentifier` column and generating the keys from the Azure function by calling `crypto.randomUUID()`. This works well and is a good sort of workaround.

**Comment by lucyzhang929** [comment]
@jnsvd a new extension bundle has been released with extra logging added. Could you try your scenario again to see if you are still seeing the same issue and provide debug logs? Thank you!
