### ISSUE TITLE
SQL trigger stopped working intermittently [System.ArgumentNullException : Value cannot be null]

### ISSUE THREAD

**Issue by huidongl** [Azure/azure-functions-sql-extension#856]
Logic App standard build-in SQL trigger "When a row is updated" has been working fine but suddenly stopped working since 2023-04-26. No changes made for the logic app network, or the SQL server. Found errors in the function log table. 

There was a version update on 4/26/3023, where Function extension version has been updated to 1.15.24.0, we changed the version back to 1.11.15.0, however it only worked for a day and kept failing after then. Restarted the Logic App multiple times, the function keeps failing to start. 

The exception is complaining connectionString is null. However, this trigger used the **Managed Identity** to create connection, and there is no connectionString at all. 

Below is the function exception at **Host.Startup**:

```
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'Functions.august_poc' ---> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException : Value cannot be null. (Parameter 'connectionString')
   at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerBinding`1..ctor(String connectionString,String tableName,ParameterInfo parameter,IHostIdProvider hostIdProvider,ILogger logger,IConfiguration configuration)
   End of inner exception
   at System.RuntimeMethodHandle.InvokeMethod(Object target,Span`1& arguments,Signature sig,Boolean constructor,Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr,Binder binder,Object[] parameters,CultureInfo culture)
   at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context)
   at async Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\CompositeTriggerBindingProvider.cs : 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 172
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 149
   End of inner exception
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 157
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 85

Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'Functions.august_poc' ---> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException : Value cannot be null. (Parameter 'connectionString')
   at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerBinding`1..ctor(String connectionString,String tableName,ParameterInfo parameter,IHostIdProvider hostIdProvider,ILogger logger,IConfiguration configuration)
   End of inner exception
   at System.RuntimeMethodHandle.InvokeMethod(Object target,Span`1& arguments,Signature sig,Boolean constructor,Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr,Binder binder,Object[] parameters,CultureInfo culture)
   at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context)
   at async Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\CompositeTriggerBindingProvider.cs : 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 172
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 149
   End of inner exception
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 157
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 85



```

**Comment by dzsquared** [comment]
Managed Identity is the authentication type, but not the server or database name.  This information is still contained in a connection string - which is required for use of this library.
