### ISSUE TITLE
WaitForProductChanges() timeouts in SqlTrigger integration tests

### ISSUE THREAD

**Issue by barbaravaldez** [Azure/azure-functions-sql-extension#905]
Filing an issue to keep track of pipeline failures, in case that this intermittent issue happens in future runs again.

Stack trace:
   at Microsoft.Azure.WebJobs.Extensions.Sql.Tests.Common.TestUtils.TimeoutAfter[TResult](Task`1 task, TimeSpan timeout, String message) in D:\a\1\s\test\Common\TestUtils.cs:line 320
   at Microsoft.Azure.WebJobs.Extensions.Sql.Tests.Integration.SqlTriggerBindingIntegrationTestBase.WaitForProductChanges(Int32 firstId, Int32 lastId, SqlChangeOperation operation, Func`1 actions, Func`2 getName, Func`2 getCost, Int32 timeoutMs, String messagePrefix) in D:\a\1\s\test\Integration\SqlTriggerBindingIntegrationTestBase.cs:line 122
   at Microsoft.Azure.WebJobs.Extensions.Sql.Tests.Integration.SqlTriggerBindingIntegrationTests.MultiHostTriggerTest(SupportedLanguages lang) in D:\a\1\s\test\Integration\SqlTriggerBindingIntegrationTests.cs:line 441

**Comment by chlafreniere** [comment]
@barbaravaldez @VasuBhog did we make any headway here?

**Comment by VasuBhog** [comment]
@chlafreniere, Product Pipelines have been green since this was last noted (so to my knowledge we have only seen this once). Therefore this only falls into the flaky test once as of now. Not sure if we want to keep this issue open here or track it in the wiki. Something we can discuss in the meeting tomorrow.

**Comment by VasuBhog** [comment]
Pipeline Error: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=208886&view=ms.vss-test-web.build-test-results-tab&runId=2635854&resultId=100183&paneView=debug

**Comment by Charles-Gagnon** [comment]
Added to wiki, will track there.
