### ISSUE TITLE
Failure to start SQL trigger on .NET 7

### ISSUE THREAD

**Issue by Stxtics** [Azure/azure-functions-sql-extension#920]
Due to project dependencies, I'm working with a function app that targets .NET 7 on an isolated process on Azure functions v4. 

On Friday, I started using this package as I wanted to make use of the SQL Triggers functionality. I had it working with a table for an initial test but on Monday I made some changes to use a new table. Since that, I have been dealing with an issue that I can't seem to figure out. So far the only fix I've found is switching to target .NET 6 (which requires commenting out a bunch of existing code in the project due to project dependencies). Unless I'm missing something I thought that .NET 7 is supported with this package, even though it targets .NET 6. 

Here is the exception output:

Failed to start SQL trigger listener for table: '', function ID: ''. Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'For detailed output, run func with --verbose flag.
at System.Configuration.ConfigurationManager.EnsureConfigurationSystem()
at System.Configuration.ConfigurationManager.PrepareConfigSystem()
at System.Configuration.ConfigurationManager.GetSection(String sectionName)
at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager.FetchConfigurationSection[T](String name)
at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager..cctor()
--- End of inner exception stack trace ---
at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
at Microsoft.Azure.WebJobs.Extensions.Sql.SqlBindingUtilities.OpenAsyncWithSqlErrorHandling(SqlConnection connection, CancellationToken cancellationToken)
at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.StartAsync(CancellationToken cancellationToken)

Apologies if the issue is something trivial on my end or not related to this repo. 
If so, any suggestions would be greatly appreciated.

**Comment by keithnicholson** [comment]
Good day!  I have experienced a similar issue recently.  I get the same error even on a SqlInput trigger that was working.  I have a [repo]( https://github.com/keithnicholson/SqlExtensions) that demonstrates. 

The key difference is the version of the Extensions.Sql chosen.  If I use the 2.x version no problem.  But as soon as I execute with a 3.X I get the error:

`[2023-09-13T02:35:43.326Z] Executed 'Functions.GetToDos' (Failed, Id=d156bf2f-b79f-4e5a-9431-96ac4e1ce950, Duration=247ms)
[2023-09-13T02:35:43.330Z] System.Private.CoreLib: Exception while executing function: Functions.GetToDos. Microsoft.Data.SqlClient: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception. System.Configuration.ConfigurationManager: Could not load file or assembly 'System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`


What is strange is another project that I had working about 10 days ago with all three SQL items, input, output, and bindings was working.  Then suddenly this weekend it stopped.  I have tried recreating a number of times and they still fail.

What has happened?

**Comment by keithnicholson** [comment]
Do I understand that GA will only be for .Net 6?


I posted here as well as in the link MaddyDev has above.

**Comment by Charles-Gagnon** [comment]
We are working on getting a version of the extension out that rolls back the change which broke this to immediately unblock people, and then as Maddy said we will be working to find a long term fix that won't break .NET 7 as well for GA.

**Comment by MaddyDev** [comment]
@keithnicholson Were you able to successfully run a trigger with .NET 7 and [3.0.341-preview](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Sql/3.0.341-preview) package?

**Comment by Stxtics** [comment]
@MaddyDev I haven't been able to run a trigger on .NET 7 with the 3.0.341-preview package since last week I believe if that's any help. (Same error as first post)

**Comment by keithnicholson** [comment]
@MaddyDev  I don't recall if it was 3.0.341 or 3.0.343.  I would imagine it was 3.0.343 since I had not started working on this until late August.  Sadly, I had not been committing the work to a local repo to validate which one I had before I updated every dependency.

I have tried taking it back to both of these and earlier one, yet still no difference.

**Comment by MaddyDev** [comment]
> @MaddyDev I haven't been able to run a trigger on .NET 7 with the 3.0.341-preview package since last week I believe if that's any help. (Same error as first post)

@Stxtics Thank you, just double checking again: you were able to successfully run a SQL trigger binding function with .NET 7 before? Or is it an input/output binding?

**Comment by Stxtics** [comment]
> > @MaddyDev I haven't been able to run a trigger on .NET 7 with the 3.0.341-preview package since last week I believe if that's any help. (Same error as first post)
> 
> @Stxtics Thank you, just double checking again: you were able to successfully run a SQL trigger binding function with .NET 7 before? Or is it an input/output binding?

@MaddyDev Yes the SQL trigger functionality. I believe it worked on Friday for an initial test. then on Monday I couldn't get it to work.

**Comment by MaddyDev** [comment]
@Stxtics, @keithnicholson We have released a new package addressing the issue that's affecting .NET 7. This should be resolved, can you confirm if you're able to run a SQL trigger successfully. Thanks.

**Comment by keithnicholson** [comment]
@maddydev
  I'll give it a try today.  Thanks.

Best regards,
Keith Nicholson
________________________________

**Comment by Stxtics** [comment]
@MaddyDev not sure that I'll be able to test this soon so I'm happy for the issue to be closed if confident enough it has been fixed.

**Comment by MaddyDev** [comment]
Closing this as fixed by the new release [3.0.433-preview](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Sql/3.0.433-preview)

**Comment by keithnicholson** [comment]
I was able to do a sqlinput.  It worked.  Having an issue with the sqloutput.  I'll get back to you tomorrow.

**Comment by keithnicholson** [comment]
All works great with the latest.

Thank you!
