### ISSUE TITLE
How do I execute this project?

### ISSUE THREAD

**Issue by Kedar782** [Azure/azure-functions-sql-extension#930]
I only want to execute the trigger part for SQL.

**Comment by Charles-Gagnon** [comment]
We have docs here : https://github.com/Azure/azure-functions-sql-extension/blob/main/docs/BindingsOverview.md#trigger-binding

And samples here : https://github.com/Azure/azure-functions-sql-extension/tree/main/samples/samples-csharp/TriggerBindingSamples (see other folders for other languages)

Let us know if you still have any questions!

**Comment by Kedar782** [comment]
I read it.
I see you have created the database in the project.
I only want to execute the samples-python from vs code.
How do I execute the code from the VS Code?
Is it possible later on I want to add my database connection in the project to monitor my project.

Please guide me I downloaded the entire main branch and then I hit 

func start --build
But I'm getting errors in the cmd What I'm doing wrong? I installed the azure functions extensions

**Comment by Kedar782** [comment]
@Charles-Gagnon 

 Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ProductsTrigger'. Microsoft.Azure.WebJobs.Extensions.Sql: ConnectionStringSetting 'SqlConnectionString' is empty in your function app settings, please update the setting with a valid SQL connection string.
[2023-09-25T19:06:56.176Z] Error indexing method 'Functions.ProductsTrigger'
[2023-09-25T19:06:56.179Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ProductsTrigger'. Microsoft.Azure.WebJobs.Extensions.Sql: ConnectionStringSetting 'SqlConnectionString' is empty in your function app settings, please update the setting with a valid SQL connection string.
[2023-09-25T19:06:56.184Z] Function 'Functions.ProductsTrigger' failed indexing and will be disabled.
[2023-09-25T19:06:56.187Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ProductsTriggerLeasesTableName'. Microsoft.Azure.WebJobs.Extensions.Sql: ConnectionStringSetting 'SqlConnectionString' is empty in your function app settings, please update the setting with a valid SQL connection string.
[2023-09-25T19:06:56.190Z] Error indexing method 'Functions.ProductsTriggerLeasesTableName'
[2023-09-25T19:06:56.192Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ProductsTriggerLeasesTableName'. Microsoft.Azure.WebJobs.Extensions.Sql: ConnectionStringSetting 'SqlConnectionString' is empty in your function app settings, please update the setting with a valid SQL connection string.



The listener for function 'Functions.TimerTriggerProducts' was unable to start.
[2023-09-25T19:13:31.254Z] The listener for function 'Functions.TimerTriggerProducts' was unable to start. Azure.Core: Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry. (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)) (No connection could be made because the target machine actively refused it. (127.0.0.1:10000)). Azure.Core: No connection could be made because the target machine actively refused it. (127.0.0.1:10000). System.Net.Http: No connection could be made because the target machine actively refused it. (127.0.0.1:10000). System.Net.Sockets: No connection could be made because the target machine actively refused it.
[2023-09-25T19:13:31.263Z] Host started (395363ms)
[2023-09-25T19:13:31.264Z] Job host started
[2023-09-25T19:13:31.280Z] The 'ProductsTrigger' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ProductsTrigger'. Microsoft.Azure.WebJobs.Extensions.Sql: ConnectionStringSetting 'SqlConnectionString' is empty in your function app settings, please update the setting with a valid SQL connection string.
[2023-09-25T19:13:31.283Z] The 'ProductsTriggerLeasesTableName' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ProductsTriggerLeasesTableName'. Microsoft.Azure.WebJobs.Extensions.Sql: ConnectionStringSetting 'SqlConnectionString' is empty in your function app settings, please update the setting with a valid SQL connection string.


Authorization:REDACTED
[2023-09-25T19:13:17.090Z]    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
[2023-09-25T19:13:17.096Z] client assembly: Azure.Storage.Blobs
[2023-09-25T19:13:17.098Z]    at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
[2023-09-25T19:13:17.104Z]    at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2023-09-25T19:13:17.106Z]    at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2023-09-25T19:13:19.087Z] Request [26ef9b18-cddc-40eb-968e-371764a0e9fc] exception Azure.RequestFailedException: No connection could be made because the target machine actively refused it. (127.0.0.1:10001)
[2023-09-25T19:13:19.090Z]  ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:10001)
[2023-09-25T19:13:19.092Z]  ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
[2023-09-25T19:13:19.094Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[2023-09-25T19:13:19.096Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[2023-09-25T19:13:19.098Z]    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
[2023-09-25T19:13:19.100Z]    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2023-09-25T19:13:19.106Z]    --- End of inner exception stack trace ---
[2023-09-25T19:13:19.107Z]    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2023-09-25T19:13:19.110Z]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-09-25T19:13:19.112Z]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-09-25T19:13:19.114Z]    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
[2023-09-25T19:13:19.120Z]    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
[2023-09-25T19:13:19.122Z]    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-09-25T19:13:19.124Z]    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[2023-09-25T19:13:19.126Z]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[2023-09-25T19:13:19.128Z]    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
[2023-09-25T19:13:19.131Z]    --- End of inner exception stack trace ---
[2023-09-25T19:13:19.135Z] Request [5a526b04-ca73-4598-ae51-af541d5a8ee2] exception Azure.RequestFailedException: No connection could be made because the target machine actively refused it. (127.0.0.1:10000)
[2023-09-25T19:13:19.137Z]    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
[2023-09-25T19:13:19.139Z]  ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:10000)
[2023-09-25T19:13:19.141Z]    at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
[2023-09-25T19:13:19.145Z]    at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2023-09-25T19:13:19.143Z]  ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
[2023-09-25T19:13:19.150Z]    at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2023-09-25T19:13:19.152Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[2023-09-25T19:13:19.156Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[2023-09-25T19:13:19.158Z]    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
[2023-09-25T19:13:19.160Z]    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2023-09-25T19:13:19.162Z]    --- End of inner exception stack trace ---
[2023-09-25T19:13:19.168Z]    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2023-09-25T19:13:19.169Z] An unhandled exception has occurred. Host is shutting down.
[2023-09-25T19:13:19.170Z]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-09-25T19:13:19.172Z] Azure.Core: No connection could be made because the target machine actively refused it. (127.0.0.1:10001). System.Net.Http: No connection could be made because the target machine actively refused it. (127.0.0.1:10001). System.Net.Sockets: No connection could be made because the target machine actively refused it.
[2023-09-25T19:13:19.174Z]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-09-25T19:13:19.182Z]    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
[2023-09-25T19:13:19.184Z]    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
[2023-09-25T19:13:19.186Z]    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-09-25T19:13:19.187Z]    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[2023-09-25T19:13:19.189Z]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

**Comment by Charles-Gagnon** [comment]
We do not have the ability to directly run the samples from our repo, they are meant more as a guide for someone getting started to see how to do certain things. 

The error you're seeing seems to be because you have not defined a connection string

`ConnectionStringSetting 'SqlConnectionString' is empty in your function app settings, please update the setting with a valid SQL connection string.`

I would suggest starting with your own function project using [Azure Function Core Tools](https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Cisolated-process%2Cnode-v4%2Cpython-v2%2Chttp-trigger%2Ccontainer-apps&pivots=programming-language-csharp) and then using our README to get started making a SQL trigger from there.

**Comment by Charles-Gagnon** [comment]
It might be easier to start with an empty project and then copy over our samples to that project - that way you don't have to worry about anything else in our repo causing problems. But making changes to our project locally is fine too if you want to get started there! For example, you can add the connection string to your own server here 

https://github.com/Azure/azure-functions-sql-extension/blob/main/samples/samples-csharp/local.settings.json#L6

To get a config that is similar to what you'd do in your own project.

And then yes, you can use the core tools to run your project locally! That's what `func start` will do - and after that you should be able to make changes in your database and see your function execute locally.

**Comment by Kedar782** [comment]
@Charles-Gagnon 

I really appreciate your help on this.

I made changes in the project and added my connection string for the database.

Now I get this error:-

Failed to start SQL trigger listener for table: 'dbo.xrxImagesD', function ID: '8816252bf6717978'. Exception: System.InvalidOperationException: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:37:48.987Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlBindingUtilities.VerifyDatabaseSupported(SqlConnection connection, ILogger logger, CancellationToken cancellationToken)
[2023-09-25T19:37:48.991Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.StartAsync(CancellationToken cancellationToken)
[2023-09-25T19:37:48.994Z] Sending exception event: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:37:48.998Z] [channel] received 47283336-d306-481e-8085-ff9175e8c846: RpcLog
[2023-09-25T19:37:49.000Z] Received WorkerInitRequest, python version 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)], worker version 4.14.0, request ID 9e271a24-15bd-4a89-81e7-78f48e66a9a7
[2023-09-25T19:37:49.002Z] [channel] received 47283336-d306-481e-8085-ff9175e8c846: RpcLog
[2023-09-25T19:37:49.013Z] The listener for function 'Functions.ProductsTrigger' was unable to start.
[2023-09-25T19:37:49.015Z] The listener for function 'Functions.ProductsTrigger' was unable to start. Microsoft.Azure.WebJobs.Extensions.Sql: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100.
[2023-09-25T19:37:49.021Z] Host started (838ms)
[2023-09-25T19:37:49.023Z] Job host started
[2023-09-25T19:37:49.030Z] File event source initialized.
[2023-09-25T19:37:49.033Z] Debug file watch initialized.
[2023-09-25T19:37:49.040Z] Diagnostic file watch initialized.
[2023-09-25T19:37:49.042Z] Hosting started
[2023-09-25T19:37:49.044Z] Host state changed from Initialized to Running.
[2023-09-25T19:37:49.048Z] Startup operation '6ca71046-2cca-4baa-9499-e94c3c491801' completed.
[2023-09-25T19:37:49.144Z] [channel] received 47283336-d306-481e-8085-ff9175e8c846: WorkerInitResponse
[2023-09-25T19:37:49.147Z] Received WorkerInitResponse. Worker process initialized
[2023-09-25T19:37:49.150Z] Worker capabilities: [SharedMemoryDataTransfer, true], [RawHttpBodyBytes, true], [TypedDataCollection, true], [WorkerStatus, true], [RpcHttpTriggerMetadataRemoved, true], [RpcHttpBodyOnly, true]
[2023-09-25T19:37:49.275Z] Worker metadata: { "runtimeName": "python", "runtimeVersion": "3.10", "workerVersion": "4.14.0", "workerBitness": "AMD64" }
[2023-09-25T19:37:49.281Z] Updating capabilities: { "SharedMemoryDataTransfer": "true", "RawHttpBodyBytes": "true", "TypedDataCollection": "true", "WorkerStatus": "true", "RpcHttpTriggerMetadataRemoved": "true", "RpcHttpBodyOnly": "true" }
[2023-09-25T19:37:49.286Z] Adding jobhost language worker channel for runtime: python. workerId:47283336-d306-481e-8085-ff9175e8c846
[2023-09-25T19:37:49.291Z] Setting up FunctionInvocationBuffer for function: 'ProductsTrigger' with functionId: 'e1a581fa-6845-4039-a745-92bb12f69fe7'
[2023-09-25T19:37:49.297Z] Sending FunctionLoadRequest for function: 'ProductsTrigger' with functionId: 'e1a581fa-6845-4039-a745-92bb12f69fe7'
[2023-09-25T19:37:49.303Z] Worker process started and initialized.
[2023-09-25T19:37:49.307Z] [channel] received 47283336-d306-481e-8085-ff9175e8c846: RpcLog
[2023-09-25T19:37:49.309Z] Received WorkerLoadRequest, request ID 9e271a24-15bd-4a89-81e7-78f48e66a9a7, function_id: e1a581fa-6845-4039-a745-92bb12f69fe7,function_name: ProductsTrigger,
[2023-09-25T19:37:49.310Z] [channel] received 47283336-d306-481e-8085-ff9175e8c846: RpcLog
[2023-09-25T19:37:49.313Z] [channel] received 47283336-d306-481e-8085-ff9175e8c846: FunctionLoadResponse
[2023-09-25T19:37:49.313Z] Successfully processed FunctionLoadRequest, request ID: 9e271a24-15bd-4a89-81e7-78f48e66a9a7, function ID: e1a581fa-6845-4039-a745-92bb12f69fe7,function Name: ProductsTrigger
[2023-09-25T19:37:49.317Z] Received FunctionLoadResponse for function: 'ProductsTrigger' with functionId: 'e1a581fa-6845-4039-a745-92bb12f69fe7'.
[2023-09-25T19:37:51.036Z] Retrying to start listener for function 'Functions.ProductsTrigger' (Attempt 1)
[2023-09-25T19:37:51.048Z] Failed to start SQL trigger listener for table: 'dbo.xrxImagesD', function ID: '8816252bf6717978'. Exception: System.InvalidOperationException: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:37:51.053Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlBindingUtilities.VerifyDatabaseSupported(SqlConnection connection, ILogger logger, CancellationToken cancellationToken)
[2023-09-25T19:37:51.055Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.StartAsync(CancellationToken cancellationToken)
[2023-09-25T19:37:51.057Z] Sending exception event: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:37:51.059Z] The listener for function 'Functions.ProductsTrigger' was unable to start.
[2023-09-25T19:37:51.061Z] The listener for function 'Functions.ProductsTrigger' was unable to start. Microsoft.Azure.WebJobs.Extensions.Sql: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100.
[2023-09-25T19:37:55.317Z] Retrying to start listener for function 'Functions.ProductsTrigger' (Attempt 2)
[2023-09-25T19:37:55.323Z] Failed to start SQL trigger listener for table: 'dbo.xrxImagesD', function ID: '8816252bf6717978'. Exception: System.InvalidOperationException: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:37:55.325Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlBindingUtilities.VerifyDatabaseSupported(SqlConnection connection, ILogger logger, CancellationToken cancellationToken)
[2023-09-25T19:37:55.327Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.StartAsync(CancellationToken cancellationToken)
[2023-09-25T19:37:55.329Z] Sending exception event: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:37:55.331Z] The listener for function 'Functions.ProductsTrigger' was unable to start.
[2023-09-25T19:37:55.337Z] The listener for function 'Functions.ProductsTrigger' was unable to start. Microsoft.Azure.WebJobs.Extensions.Sql: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100.
[2023-09-25T19:38:00.692Z] Retrying to start listener for function 'Functions.ProductsTrigger' (Attempt 3)
[2023-09-25T19:38:00.702Z] Failed to start SQL trigger listener for table: 'dbo.xrxImagesD', function ID: '8816252bf6717978'. Exception: System.InvalidOperationException: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:38:00.705Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlBindingUtilities.VerifyDatabaseSupported(SqlConnection connection, ILogger logger, CancellationToken cancellationToken)
[2023-09-25T19:38:00.707Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.StartAsync(CancellationToken cancellationToken)
[2023-09-25T19:38:00.712Z] Sending exception event: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:38:00.714Z] The listener for function 'Functions.ProductsTrigger' was unable to start.
[2023-09-25T19:38:00.716Z] The listener for function 'Functions.ProductsTrigger' was unable to start. Microsoft.Azure.WebJobs.Extensions.Sql: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100.
[2023-09-25T19:38:09.567Z] Retrying to start listener for function 'Functions.ProductsTrigger' (Attempt 4)
[2023-09-25T19:38:09.574Z] Failed to start SQL trigger listener for table: 'dbo.xrxImagesD', function ID: '8816252bf6717978'. Exception: System.InvalidOperationException: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:38:09.576Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlBindingUtilities.VerifyDatabaseSupported(SqlConnection connection, ILogger logger, CancellationToken cancellationToken)
[2023-09-25T19:38:09.578Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.StartAsync(CancellationToken cancellationToken)
[2023-09-25T19:38:09.580Z] Sending exception event: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:38:09.583Z] The listener for function 'Functions.ProductsTrigger' was unable to start.
[2023-09-25T19:38:09.588Z] The listener for function 'Functions.ProductsTrigger' was unable to start. Microsoft.Azure.WebJobs.Extensions.Sql: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100.
[2023-09-25T19:38:29.006Z] Retrying to start listener for function 'Functions.ProductsTrigger' (Attempt 5)
[2023-09-25T19:38:29.012Z] Failed to start SQL trigger listener for table: 'dbo.xrxImagesD', function ID: '8816252bf6717978'. Exception: System.InvalidOperationException: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:38:29.015Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlBindingUtilities.VerifyDatabaseSupported(SqlConnection connection, ILogger logger, CancellationToken cancellationToken)
[2023-09-25T19:38:29.017Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.StartAsync(CancellationToken cancellationToken)
[2023-09-25T19:38:29.019Z] Sending exception event: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:38:29.021Z] The listener for function 'Functions.ProductsTrigger' was unable to start.
[2023-09-25T19:38:29.026Z] The listener for function 'Functions.ProductsTrigger' was unable to start. Microsoft.Azure.WebJobs.Extensions.Sql: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100.
[2023-09-25T19:38:31.624Z] Host instance '00000000000000000000000048546A02' failed to acquire host lock lease: Azure.Core: No connection could be made because the target machine actively refused it. (127.0.0.1:10000). System.Net.Http: No connection could be made because the target machine actively refused it. (127.0.0.1:10000). System.Net.Sockets: No connection could be made because the target machine actively refused it.
[2023-09-25T19:38:59.727Z] Retrying to start listener for function 'Functions.ProductsTrigger' (Attempt 6)
[2023-09-25T19:38:59.734Z] Failed to start SQL trigger listener for table: 'dbo.xrxImagesD', function ID: '8816252bf6717978'. Exception: System.InvalidOperationException: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:38:59.737Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlBindingUtilities.VerifyDatabaseSupported(SqlConnection connection, ILogger logger, CancellationToken cancellationToken)
[2023-09-25T19:38:59.739Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.StartAsync(CancellationToken cancellationToken)
[2023-09-25T19:38:59.740Z] Sending exception event: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100
[2023-09-25T19:38:59.747Z] The listener for function 'Functions.ProductsTrigger' was unable to start.
[2023-09-25T19:38:59.749Z] The listener for function 'Functions.ProductsTrigger' was unable to start. Microsoft.Azure.WebJobs.Extensions.Sql: SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100.

This is how my locals.setting.json looks like
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "SqlConnectionString": "Server=Myserver.database.windows.net;Database=MyDataBase;User Id=myUSerId;Password=myPassword;",
    "Sp_SelectCost": "SelectProductsCost",
    "ProductCost": 100
  }
}

My host.json did not change anything
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    },
    "logLevel": {
      "default": "Trace"
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Preview",
    "version": "[4.*, 5.0.0)"
  }
}
and my function.json is below


{
    "bindings": [
      {
        "name": "changes",
        "type": "sqlTrigger",
        "direction": "in",
        "tableName": "dbo.xrxImagesD",
        "connectionStringSetting": "SqlConnectionString"
      }
    ],
    "disabled": false
  }
  
  I go to the directory azure-functions-sql-extension\samples\samples-python> and then hit func start --build to execute the project
  
 Do you know what I'm doing wrong here?
 I have done this setting on my database for which I'm adding triggers

ALTER DATABASE [SampleDatabase]
SET CHANGE_TRACKING = ON
(CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON);

ALTER TABLE [dbo].[ToDo]
ENABLE CHANGE_TRACKING;


  Again I really appreciate your help on this.

**Comment by Charles-Gagnon** [comment]
`SQL bindings require a database compatibility level of 130 or higher to function. Current compatibility level = 100`

The database you've specified has the compat level at 100, which unfortunately doesn't support the OPENJSON statement that is required by our extension. See https://github.com/Azure/azure-functions-sql-extension/blob/main/README.md#supported-sql-server-versions for more details. So you'll need to change the compat level to 130 or higher to be able to use the SQL extension.

**Comment by Kedar782** [comment]
@Charles-Gagnon 
Thanks it is working fine on my DB and locally.
Whenever I'm making changes on the SSMS in the table then I can get the changes in my azure function app which I'm running locally. But when I make changes using the published app in the database those changes is not reflecting in the locally executed program. Do I have to publish my Azure function for this?

Also, after getting changes in the azure function I want to upload the image on the blob container and then I want to delete the binary string in the database using the Azure function code Can I do that?

Please let me know if you have any questions for me. I really appreciate your help and guidance.

**Comment by Charles-Gagnon** [comment]
Could you explain this a bit more? ` But when I make changes using the published app in the database those changes is not reflecting in the locally executed program`

What "app" is this? A function app or just some other application that is making modifications to your DB?

About your second question - you definitely can! Look into [blob output bindings](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob?tabs=isolated-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp) and [SQL input bindings](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-input?tabs=isolated-process%2Cnodejs-v4&pivots=programming-language-csharp#http-trigger-delete-rows). You can have multiple bindings on one function - so you could you have your SQL-triggered function then also trigger the blob output binding and sql input binding in the same function.

**Comment by Kedar782** [comment]
@Charles-Gagnon 

It is the web application that is making modifications on my DB. My Azure function is not able to catch those modifications.
Even if I run that web application locally on my computer I still not able to catch changes made by that application in azure function program.

I have one more question, Can I monitor one more database in the same azure function program?

**Comment by Charles-Gagnon** [comment]
And you're sure that the database/table being modified is the same one being monitored by your function?

Yes, you can monitor multiple databases/tables - but you will need a separate function for each.

**Comment by Kedar782** [comment]
Yes, it is monitoring same database but UserId in the connection string is different in web application. Is that the reason?

Can you please give me example how can I monitor the different database from same Azure Function?
I need to have two connection strings in function.json file and also do I need to use two index.json file?

Also, I also need to do the bulk transfer means I want to transfer all entries in my database to blob container.

How do I access the all entries in the database using this azure function program.(I need to access all entries in the database in loop)

**Comment by Charles-Gagnon** [comment]
User ID shouldn't make a difference. Could you file a separate issue for that and we can follow up with helping investigate that specific issue?

Unfortunately you can't monitor two separate DBs from the same function. You will need to create a separate function for each. These functions can be in the same function app though.

SQL input bindings can be used to retrieve data from a database, and then you'd use an output binding (such as the blob output binding) to take that data and push it elsewhere. The docs and samples should help with getting that set up.

**Comment by Kedar782** [comment]
Sure. I will create a new issue for this.

So you are saying we can publish two different projects in one Azure function App?

I will look into documents for the Bulk migrations.

@Charles-Gagnon Thanks for your help.

**Comment by Charles-Gagnon** [comment]
You can have 1 project that contains multiple functions (see the Azure Functions docs for information on how to do that using the core tools or something like VS Code), or you could split them into separate projects. It's up to you what one you'd prefer.
