### ISSUE TITLE
Failed to start SQL trigger - Microsoft.Data.SqlClient is not supported on this platform.

### ISSUE THREAD

**Issue by charliecheng23** [Azure/azure-functions-sql-extension#975]
- Azure Functions SQL Extension or Extension Bundle Version:  4.0.5455
- Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- Is this a deployed or local function: local computer window 10  Enterprise for Virtual Desktop
- What type of Database are you using? -Microsoft SQL Azure (RTM) - 12.0.2000.8   Aug 28 2023 13:51:45   Copyright (C) 2022 Microsoft Corporation 
- List any custom settings for your function app. 

Steps to Reproduce:

1. Run func start
2. Below error to listener to sql trigger -

Failed to start SQL trigger listener for table: 'dbo.STG_WATER_GW_DIVERSION_AUTHORIZATION', function ID: '5c477fd9feb82cd5'. Exception: System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.
[2023-11-29T04:06:51.544Z]    at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
[2023-11-29T04:06:51.547Z]    at Microsoft.Azure.WebJobs.Extensions.Sql.SqlTriggerListener`1.StartAsync(CancellationToken cancellationToken)
[2023-11-29T04:06:51.549Z] The listener for function 'Functions.appchangescdegwauth' was unable to start.
[2023-11-29T04:06:51.551Z] The listener for function 'Functions.appchangescdegwauth' was unable to start. Microsoft.Data.SqlClient: Microsoft.Data.SqlClient is not supported on this platform.

**Comment by lucyzhang929** [comment]
@charliecheng23 This issue seems similar to https://github.com/Azure/Azure-Functions/issues/1370. I will transfer to the Azure Functions host repository for further investigation.
